// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/masyarakat/dashboard": {
    params: {};
  };
  "/masyarakat/jadwal": {
    params: {};
  };
  "/masyarakat/gamifikasi": {
    params: {};
  };
  "/masyarakat/statistik": {
    params: {};
  };
  "/pengelola/dashboard": {
    params: {};
  };
  "/pengelola/jadwal-penjemputan": {
    params: {};
  };
  "/pengelola/monitoring": {
    params: {};
  };
  "/pengelola/penjualan": {
    params: {};
  };
  "/pengelola/verifikasi": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/masyarakat/dashboard" | "/masyarakat/jadwal" | "/masyarakat/gamifikasi" | "/masyarakat/statistik" | "/pengelola/dashboard" | "/pengelola/jadwal-penjemputan" | "/pengelola/monitoring" | "/pengelola/penjualan" | "/pengelola/verifikasi";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./pages/masyarakat/Dashboard.tsx": {
    id: "pages/masyarakat/Dashboard";
    page: "/masyarakat/dashboard";
  };
  "./pages/masyarakat/JadwalSetor.tsx": {
    id: "pages/masyarakat/JadwalSetor";
    page: "/masyarakat/jadwal";
  };
  "./pages/masyarakat/Gamifikasi.tsx": {
    id: "pages/masyarakat/Gamifikasi";
    page: "/masyarakat/gamifikasi";
  };
  "./pages/masyarakat/Statistik.tsx": {
    id: "pages/masyarakat/Statistik";
    page: "/masyarakat/statistik";
  };
  "./pages/pengelola/Dashboard.tsx": {
    id: "pages/pengelola/Dashboard";
    page: "/pengelola/dashboard";
  };
  "./pages/pengelola/JadwalPenjemputan.tsx": {
    id: "pages/pengelola/JadwalPenjemputan";
    page: "/pengelola/jadwal-penjemputan";
  };
  "./pages/pengelola/Monitoring.tsx": {
    id: "pages/pengelola/Monitoring";
    page: "/pengelola/monitoring";
  };
  "./pages/pengelola/Penjualan.tsx": {
    id: "pages/pengelola/Penjualan";
    page: "/pengelola/penjualan";
  };
  "./pages/pengelola/Verifikasi.tsx": {
    id: "pages/pengelola/Verifikasi";
    page: "/pengelola/verifikasi";
  };
};